line_length: 140
type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 600
  error: 800

type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: # only min_length
    error: 1 # only error
reporter: "xcode"
